### ISSUE TITLE
How to use for publicizing nuget packages, like Krafs.Rimworld.Ref?

### ISSUE THREAD

**Issue by Taranchuk** [krafs/Publicizer#1]
Couldn't figure it out on my own. Mind uploading an example in README?

**Comment by krafs** [comment]
@Taranchuk 
Good input. I'll look into it.

In the meantime, [here's an example](https://gist.github.com/krafs/5f6c75ab198823e270cdaaa1146e693d) with **Krafs.Rimworld.Ref**. It's a barebone example of a csproj-file that publicizes the most common assemblies used in Rimworld modding.

Make sure you're referencing **Krafs.Rimworld.Ref** as a PackageReference in your project, and then specify the names of the assemblies within that package that you want publicized. For Rimworld, it's usually **Assembly-CSharp**, and sometimes **UnityEngine.CoreModule**. For a complete list of assemblies within a PackageReference, you can open it up with e.g. [7zip](https://www.7-zip.org/) and find the folder with all the assemblies. It's usually _lib/_, but sometimes _ref/._

Try it and let me know how it goes!
