### ISSUE TITLE
How to publicize generic class/fields?

### ISSUE THREAD

**Issue by newbie-forever** [krafs/Publicizer#119]
I am trying to publicize harmony mono cecil collection, using the following code

  &lt;ItemGroup>
    &lt;Publicize Include="0Harmony:Mono.Collections.Generic.Collection`1" />
    &lt;Publicize Include="0Harmony:Mono.Collections.Generic.Collection`1.Add" />
  &lt;/ItemGroup>

But it's not working. Mono.Collections.Generic.Collection is defined as private class Collection<T> {
public void Add(T item) {}
}

**Comment by krafs** [comment]
It's a bit hard to read your code due to the formatting, but I believe this is what you're asking for:
```xml
<Publicize Include="0Harmony:Mono.Collections.Generic.Collection`1.Add" />
```
This should make the type itself, and the Add-function, public.

See [this ](https://github.com/bbradson/Performance-Fish/blob/main/Source/PerformanceFish/Directory.Build.Props#L82)for other examples of specifying specific members on generic classes.

Does this work?

**Comment by newbie-forever** [comment]
> It's a bit hard to read your code due to the formatting, but I believe this is what you're asking for:
> 
> ```
> <Publicize Include="0Harmony:Mono.Collections.Generic.Collection`1.Add" />
> ```
> 
> This should make the type itself, and the Add-function, public.
> 
> See [this ](https://github.com/bbradson/Performance-Fish/blob/main/Source/PerformanceFish/Directory.Build.Props#L82)for other examples of specifying specific members on generic classes.
> 
> Does this work?

It's a bit weird that even though the ILSpy says that both of the class and method are public, but the visual studio still says they have a level of protection. 
[0Harmony.E9B3E22A97F5EAD842B78B065197346D.zip](https://github.com/user-attachments/files/17088533/0Harmony.E9B3E22A97F5EAD842B78B065197346D.zip)

**Comment by newbie-forever** [comment]
Here is the code snippet using the class
```
internal static class FreePatching {
	[FreePatch]
	internal static void Patch(ModuleDefinition module) {
		var type = module.GetType(typeof(DefDatabase<>).FullName);
		var method = type.FindMethod(nameof(DefDatabase<Def>.GetNamed));
		var il = method.Body.GetILProcessor();
		var convert = new GenericInstanceMethod(module.ImportReference(typeof(TransferDefsModSettings).Method(nameof(TransferDefsModSettings.ConvertDefName))));
		convert.GenericArguments.Add(type.GenericParameters[0]);
		method.Body.Instructions.InsertRange(0, [
			il.Create(OpCodes.Ldarga_S, method.Parameters[0]),
			il.Create(OpCodes.Call, convert)
		]);
	}
}
```

**Comment by newbie-forever** [comment]
> It's a bit hard to read your code due to the formatting, but I believe this is what you're asking for:
> 
> ```
> <Publicize Include="0Harmony:Mono.Collections.Generic.Collection`1.Add" />
> ```
> 
> This should make the type itself, and the Add-function, public.
> 
> See [this ](https://github.com/bbradson/Performance-Fish/blob/main/Source/PerformanceFish/Directory.Build.Props#L82)for other examples of specifying specific members on generic classes.
> 
> Does this work?

It works, thank you very much
