### ISSUE TITLE
Accessing publicized members at runtime only works in Mono

### ISSUE THREAD

**Issue by krafs** [krafs/Publicizer#13]
Compiling an assembly with **AllowUnsafeBlocks** = true tells the runtime to not enforce access checks. Effectively, this is what makes publicized assemblies work.

However, it turns out this is only true for the Mono runtime. It has seemingly no effect in e.g. CoreCLR. Accessing a publicized member in any other runtime will throw a **MemberAccessException**.

In other words - Publicizer can only safely be used if run in Mono.

**Comment by ameisen** [comment]
As mentioned in #12 , properly handling `IgnoresAccessChecksToAttribute` should remedy this.

**Comment by krafs** [comment]
Closed by #28.
