### ISSUE TITLE
About unnamed namespace

### ISSUE THREAD

**Issue by h4k0t4** [krafs/Publicizer#14]
If there is an unnamed namespace within an assembly, and I don't want some items in this namespace to be publicized, how do I use it?

**Comment by krafs** [comment]
This is what you normally do with a type in a namespace:
```xml
<ItemGroup>
    <Publicize Include="MyAssembly" />
    <DoNotPublicize Include="MyAssembly:MyNamespace.MyType._privateField" />
</ItemGroup>
```

You should be able to just exclude the namespace from the type:
```xml
<ItemGroup>
    <Publicize Include="MyAssembly" />
    <DoNotPublicize Include="MyAssembly:MyType._privateField" />
</ItemGroup>
```
