### ISSUE TITLE
Compile error PublicizeAsReferenceAssemblies cannot be parsed as bool when having multiple VS projects with publicizers opened

### ISSUE THREAD

**Issue by Taranchuk** [krafs/Publicizer#45]
Works fine when only having one VS window, but breaks if keep multiple VS projects opened.

**Comment by krafs** [comment]
Hi! Thanks for the report. A few questions:

What version of Publicizer are you using?
Are both projects using the same version?
If you've updated from 1.* to 2.* in any of the projects, have you tried closing VS, deleting all .vs-, and obj-folders, and restarting VS?

**Comment by Taranchuk** [comment]
Turns out first project had 2.01 version while the second project stayed on 1 version. Updating to 2 version solved the issues. Sorry for the false alarm.

**Comment by krafs** [comment]
I remember seeing something similar during my v2.0-testing. No worries, I'm glad it was so easily resolved :)
