### ISSUE TITLE
mscorlib fails to publicize

### ISSUE THREAD

**Issue by Sl4vP0weR** [krafs/Publicizer#60]
Error CS0009 'D:\repos\UnityDebug\HotReload\obj\Debug\net4.8\PublicizedAssemblies\mscorlib.A6F21AA89703C03E666558F7C303E578\mscorlib.dll' could not be opened -- Image is too small.

**Comment by krafs** [comment]
What does your csproj look like?

And just in case - have you tried closing VS, deleting .vs/ and obj/, and restarting?

**Comment by Sl4vP0weR** [comment]
![image](https://user-images.githubusercontent.com/42337892/205433630-05d55427-628f-4a2b-af34-91441d3f35c5.png)
Tried, no changes.

**Comment by Sl4vP0weR** [comment]
Looks like versions 1.* is more stable than 2.*
But how can I publicize assembly with all code, not just references?
![image](https://user-images.githubusercontent.com/42337892/205464194-3a4a173b-edb3-4283-af32-7035aff105c0.png)

**Comment by krafs** [comment]
If you're using v1, you can keep all code in publicized assemblies by setting:
```xml
<PropertyGroup>
    <PublicizeAsReferenceAssemblies>false</PublicizeAsReferenceAssemblies>
</PropertyGroup>
```
Not sure why it's failing in mscorlib in v2 though. Will take a look.

**Comment by Sl4vP0weR** [comment]
> PublicizeAsReferenceAssemblies

Same thing as with version 2.*

**Comment by Sl4vP0weR** [comment]
> PublicizeAsReferenceAssemblies

Not changed anything.

**Comment by krafs** [comment]
Are you sure that you're referencing a mcsorlib.dll that has code? Or is it just a reference assembly? A lot of the core assemblies have reference assembly counterparts to load faster in the compiler.

**Comment by Sl4vP0weR** [comment]
> reference assembly

Not sure, I'm using Microsoft.NET.Sdk, I don't need to manually setup mscorlib reference.
I assume it's reference from to mscorlib in GAC, without publicizer there's code, with it there's empty bodies.

**Comment by krafs** [comment]
Ok. Well, `<PublicizeAsReferenceAssemblies>false</PublicizeAsReferenceAssemblies>` should work in v1. You could try and remove `obj` and restart your IDE, and see if that does anything. That property is not part of the API in v2 anymore.

I'll have a closer look at this when I find some time. And please let me know if you manage so solve it, or find some other info that might be of use.

**Comment by krafs** [comment]
Is this still an issue? Did you manage to fix it?

**Comment by Sl4vP0weR** [comment]
```xml
<PropertyGroup>
	<PublicizeAsReferenceAssemblies>false</PublicizeAsReferenceAssemblies>
</PropertyGroup>
```
Version 1.0.2 works good, but non-reference publicize not works.
Not using version 2 cause it's still not work.

**Comment by krafs** [comment]
Exactly what is the issue still? Because it all started with the error "mscorlib could not be opened -- Image is too small", right? Is that still the main issue, or is the issue that you can't see the method bodies' code?

**Comment by Sl4vP0weR** [comment]
Looks like problem is that I'm using props file where I use it.
If I place all lines directly into csproj it works.

**Comment by Sl4vP0weR** [comment]
Main issue is gone, but I have some more question, how can I contact you?

**Comment by krafs** [comment]
If the main problem of this issue is gone, then I'll close this now :thumbsup:

I think the best place for further questions and discussions is a new GitHub issue.
