### ISSUE TITLE
Publicizing Specific Members on nested types

### ISSUE THREAD

**Issue by StarFluxGames** [krafs/Publicizer#71]
Currently trying to target a `private struct` nested inside a `public class` with the following
`Kitchen.Common:Kitchen.PlayerCosmeticSubview.AttachmentPoint`.
Continuing to get the CS0122 inaccessible error.

**Comment by krafs** [comment]
Publicizer mostly references members the same way Reflection does. In the case of nested types there is a `+`-sign before the nested type, which in your case this would be:

```xml
<ItemGroup>
    <Publicize Include="Kitchen.Common:Kitchen.PlayerCosmeticSubview+AttachmentPoint" />
</ItemGroup>
```
There are other examples, like how to reference constructors: `Kitchen.PlayerCosmeticSubview..ctor`.

I can see if I can add something to the README about this. Thanks for bringing it up!
And let me know if you still can't get it working.
