### ISSUE TITLE
revert visibility modifier of overidden methods in subclasses of publicized classses

### ISSUE THREAD

**Issue by CptMoore** [krafs/Publicizer#72]
just an idea, dont know if it would work or what other issues could come of it, but...

if
```csharp
class Orignal {
    protected virtual ok() {}
}
```

gets subclassed by
```csharp
class Subclass : Orignal {
    public override ok() {}
}
```

go through the compiled assembly containing the subclass and change the visbility of the override to protected.

Would that avoid the need for the workarounds mentioned under Quirks?

**Comment by krafs** [comment]
Cool idea :) It does sound a bit more ambitious than it's worth though. I'd be worried about edge cases, and like how debugging would work with a modified assembly, and how IL-linking tools like ILMerge and ILRepack would react.

**Comment by CptMoore** [comment]
I guess if the attributes of the other issue gets implemented, this here could be done in a separate nuget package/dll/lib that just goes through the assembly @ TargetPath timely after the BuildCompile build target and finds subclasses that override / implement those publicized members using attribute information.

Our modding community (BattleTech) anyway uses dnspy and assemblies copied to mod directories. So no need to integrate with any IDEs or so. And nobody uses ILMerge/ILRepack there either.

Right now that feature would only help one person that right now has to still rely on Harmony traverse for like 6 classes if I remember correctly, only because the classes he is subclassing have some internal/private members.
