### ISSUE TITLE
Clarify: Publicise requires file name, not assembly name.

### ISSUE THREAD

**Issue by Epicguru** [krafs/Publicizer#74]
I have the following set up:
```XML
<Reference Include="CombatExtended">
  <HintPath>CombatExtended_14.dll</HintPath>
</Reference>
```
where `CombatExtended_14.dll` is simply a renamed `CombatExtended.dll`, the assembly name when imported and loaded is still `CombatExtended`.

Based on the readme line `Publicizing these assemblies is just a matter of finding out what the underlying assemblies are called` and a [reply in this other issue](https://github.com/krafs/Publicizer/issues/2#issuecomment-913991084) I incorrectly assumed that I should use the _assembly name_ (`CombatExtended`) instead of the seemingly correct _assembly file name without extension_ (`CombatExtended_14`).

Made me scratch my head for a while until I publicized all and checked the log. I don't think this is a bug, just a miscommunication. An additional line in the readme might be good.

Thanks.

**Comment by krafs** [comment]
Sorry about the confusion. Yes, I can clarify that, for sure. Thanks for opening an issue for it!
