### ISSUE TITLE
Exclude `[CompilerGenerated]` members ?

### ISSUE THREAD

**Issue by gotmachine** [krafs/Publicizer#9]
I'm running into a lot of `CS0229 Ambiguity between 'SomeClass.MemberX' and 'SomeClass.MemberX'` errors in my use case.
I'm publicizing an assembly that has a lot of :
```cs
public event Callback<object> EventX;
```
resulting in corresponding
```cs
[CompilerGenerated]
private Callback<object> EventX;
```
members in the assembly, which are turned public by the publicizer, making their use impossible.

I know I can blacklist members individually, but this is quite tedious.
Would it be possible to have an option to not publicize `[CompilerGenerated]` members ?

**Comment by krafs** [comment]
Closed by #34.
